version: "3.9"

services:
 api: 
  build:
   context: .
   #target: builder
  volumes:
   - ./app:/app
  environment:
   - LOG_LEVEL=debug
   - RELOAD=true
  command: ["-m","uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
 db:
  ports: 
   - "3307:3306"

 redis:
  ports:
   - "7000:7000"