apiVersion: v1
kind: LimitRange
metadata:
  name: taskflow-limits
  namespace: taskflow
spec:
  limits:
  - type: Container
    default:             # applied if no limits specified
      cpu: "200m"
      memory: "128Mi"
    defaultRequest:      # applied if no requests specified
      cpu: "50m"
      memory: "64Mi"
    max:                 # no container can exceed this
      cpu: "1000m"
      memory: "1Gi"
    min:                 # no container can go below this
      cpu: "10m"
      memory: "16Mi"